spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://config-server:8071
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*), /$\{path}
            - AuthorizationFilter
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment/(?<path>.*), /$\{path}
            - AuthorizationFilter

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8765/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoint:
    gateway:
      enabled: true
  health:
    vault:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
