spring:
    application:
     name: payment-service
    profiles:
      active: default
    config:
      import: optional:configserver:http://config-server:8071
    cloud:
      stream:
        kafka:
          binder:
            brokers:
              - http://kafka:9092
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/coffee-shop
            jwk-set-uri: http://keycloak:8080/realms/coffee-shop/protocol/openid-connect/certs
    kafka:
      bootstrap-servers: http://kafka:9092

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka-server:8765/eureka}
  instance:
    prefer-ip-address: true
#    hostname: localhost

server:
  port: 8082