spring:
    application:
     name: payment-service
    profiles:
      active: default
    config:
      import: optional:configserver:http://localhost:8071
    cloud:
      stream:
        kafka:
          binder:
            brokers:
              - http://localhost:9093
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/coffee-shop
            jwk-set-uri: http://localhost:8080/realms/coffee-shop/protocol/openid-connect/certs
    kafka:
      bootstrap-servers: http://localhost:9093

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8765/eureka}
  instance:
    preferIpAddress: true

server:
  port: 8082