#stage 1
#Start with a base image containing Java runtime
FROM openjdk:21-slim as build

# Add Maintainer Info
LABEL maintainer="Son Nguyen (sonnpm197@gmail.com)"

# Add the application's jar to the container
COPY build/libs/* app.jar

#unpackage jar file
RUN java -Djarmode=layertools -jar app.jar extract

#stage 2
#Same Java runtime
FROM openjdk:21-slim

#Copy unpackaged application to new container
COPY --from=build dependencies/ ./
COPY --from=build spring-boot-loader/ ./
COPY --from=build snapshot-dependencies/ ./
COPY --from=build application/ ./

#execute the application
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]