version: "3.7"
services:

  order-service:
    image: sonnpm/coffee-shop/order-service:0.0.1
    container_name: order-service
    ports:
      - "8081:8081"
    networks:
      backend:
        aliases:
          - "order-service"

  payment-service:
    image: sonnpm/coffee-shop/payment-service:0.0.1
    container_name: payment-service
    ports:
      - "8082:8082"
    networks:
      backend:
        aliases:
          - "payment-service"

volumes:
  kafka-volume:
  zookeeper-volume:
  redis_data:
  esdata1:
    driver: local

networks:
  backend:
    driver: bridge