version: "3.7"
services:

  config-server:
    image: sonnpm/coffee-shop/config-server:0.0.1
    container_name: config-server
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "config-server"

  eureka-server:
    image: sonnpm/coffee-shop/eureka-server:0.0.1
    container_name: eureka-server
    ports:
      - "8765:8765"
    networks:
      backend:
        aliases:
          - "eureka-server"
    depends_on:
      config-server:
        condition: service_started

  gateway-server:
    image: sonnpm/coffee-shop/gateway-server:0.0.1
    container_name: gateway-server
    ports:
      - "8888:8888"
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway-server"

  order-service:
    image: sonnpm/coffee-shop/order-service:0.0.1
    container_name: order-service
    ports:
      - "8081:8081"
    networks:
      backend:
        aliases:
          - "order-service"
    depends_on:
      - config-server
      - eureka-server

  payment-service:
    image: sonnpm/coffee-shop/payment-service:0.0.1
    container_name: payment-service
    ports:
      - "8082:8082"
    networks:
      backend:
        aliases:
          - "payment-service"
    depends_on:
      - config-server
      - eureka-server

volumes:
  kafka-volume:
  zookeeper-volume:
  redis_data:
  esdata1:
    driver: local

networks:
  backend:
    driver: bridge